---
  - name: Fact Finder
    hosts: localhost
    tasks:
      - name: Register Ansible Facts
        setup:
        register: ansible_facts
      - name: Print Ansible Facts
        debug:
          msg: "{{ ansible_facts }}"

